export const TWEET_CREATE_REQUEST="TWEET_CREATE_REQUEST"
export const TWEET_CREATE_SUCCESS="TWEET_CREATE_SUCCESS"
export const TWEET_CREATE_FAILURE="TWEET_CREATE_FAILURE"

export const TWEET_DELETE_REQUEST="TWEET_DELETE_REQUEST"
export const TWEET_DELETE_SUCCESS="TWEET_DELETE_SUCCESS"
export const TWEET_DELETE_FAILURE="TWEET_DELETE_FAILURE"

export const GET_ALL_TWEET_REQUEST="GET_ALL_TWEET_REQUEST"
export const GET_ALL_TWEET_SUCCESS="GET_ALL_TWEET_SUCCESS"
export const GET_ALL_TWEET_FAILURE="GET_ALL_TWEET_FAILURE"

export const GET_USERS_TWEET_REQUEST="GET_USERS_TWEET_REQUEST"
export const GET_USERS_TWEET_SUCCESS="GET_USERS_TWEET_SUCCESS"
export const GET_USERS_TWEET_FAILURE="GET_USERS_TWEET_FAILURE"

export const USER_LIKE_TWEET_REQUEST="USER_LIKE_TWEET_REQUEST"
export const USER_LIKE_TWEET_SUCCESS="USER_LIKE_TWEET_SUCCESS"
export const USER_LIKE_TWEET_FAILURE="USER_LIKE_TWEET_FAILURE"

export const LIKE_TWEET_REQUEST="LIKE_TWEET_REQUEST"
export const LIKE_TWEET_SUCCESS="LIKE_TWEET_SUCCESS"
export const LIKE_TWEET_FAILURE="LIKE_TWEET_FAILURE"

export const FIND_TWEET_BY_ID_REQUEST="FIND_TWEET_BY_ID_REQUEST"
export const FIND_TWEET_BY_ID_SUCCESS="FIND_TWEET_BY_ID_SUCCESS"
export const FIND_TWEET_BY_ID_FAILURE="FIND_TWEET_BY_ID_FAILURE"

export const ADD_COMMENT_REQUEST="COMMENT_TWEET_REQUEST"
export const ADD_COMMENT_SUCCESS="COMMENT_TWEET_SUCCESS"
export const ADD_COMMENT_FAILURE="COMMENT_TWEET_FAILURE"

export const DELETE_COMMENT_REQUEST="DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS="DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAILURE="DELETE_COMMENT_FAILURE"

export const RETWEET_CREATE_REQUEST="RETWEET_REQUEST"
export const RETWEET_CREATE_SUCCESS="RETWEET_SUCCESS"
export const RETWEET_CREATE_FAILURE="RETWEET_FAILURE"

export const REPOST_REQUEST = "REPOST_REQUEST";
export const REPOST_SUCCESS = "REPOST_SUCCESS";
export const REPOST_FAILURE = "REPOST_FAILURE";

export const UNREPOST_REQUEST = "UNREPOST_REQUEST";
export const UNREPOST_SUCCESS = "UNREPOST_SUCCESS";
export const UNREPOST_FAILURE = "UNREPOST_FAILURE";

export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAILURE = "LIKE_FAILURE";

export const UNLIKE_REQUEST = "UNLIKE_REQUEST";
export const UNLIKE_SUCCESS = "UNLIKE_SUCCESS";
export const UNLIKE_FAILURE = "UNLIKE_FAILURE";

export const FAVORITE_REQUEST = "FAVORITE_REQUEST";
export const FAVORITE_SUCCESS = "FAVORITE_SUCCESS";
export const FAVORITE_FAILURE = "FAVORITE_FAILURE";

export const UNFAVORITE_REQUEST = "UNFAVORITE_REQUEST";
export const UNFAVORITE_SUCCESS = "UNFAVORITE_SUCCESS";
export const UNFAVORITE_FAILURE = "UNFAVORITE_FAILURE";

export const GET_ALL_COMMENTS_REQUEST = "GET_ALL_COMMENTS_REQUEST";
export const GET_ALL_COMMENTS_SUCCESS = "GET_ALL_COMMENTS_SUCCESS";
export const GET_ALL_COMMENTS_FAILURE = "GET_ALL_COMMENTS_FAILURE";

